name: Docker Socket Proxy
version: "1.0.0"
slug: docker-socket-proxy
description: Secure Docker Socket Proxy using Tecnativa/docker-socket-proxy
stage: stable
startup: services
boot: auto
url: "https://github.com/DJBenson/ha-docker-socket-proxy"
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
  - i386
init: false
homeassistant_api: false
host_network: true
privileged:
  - SYS_ADMIN
docker_api: true
options:
  port: 2375
schema:
  port: port
